name: webreader_flutter
description: "A new Flutter package project."
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  webreader_flutter_platform_interface:
    path: ../webreader_flutter_platform_interface
  webreader_flutter_android:
    path: ../webreader_flutter_android
dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  plugin_platform_interface: ^2.1.7

flutter:
  plugin:
    platforms:
      android:
        default_package: webreader_flutter_android

