name: webreader_flutter
description: "A new Flutter package project."
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  platform_interface:
      path: ../webreader_flutter_platform_interface
dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  mockito: 5.4.3
  plugin_platform_interface: ^2.1.3

flutter:

