name: webreader_flutter_android
description: "A new Flutter module project."

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.10.0"
dependencies:
  flutter:
    sdk: flutter
#  platform_interface:
#    path: ../webreader_flutter_platform_interface
  webreader_flutter_platform_interface:
    path: ../webreader_flutter_platform_interface



dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  pigeon: ^15.0.2


flutter:
  plugin:
    implements: webreader_flutter
    platforms:
      android:
        package: omnivore.webreader
        pluginClass: WebReaderFlutterPlugin
        dartPluginClass: AndroidWebReaderPlatform

